version: 2
jobs:
    build:
      docker:
        - image: circleci/python:3.4  # primary container for the build job
      steps:
        - checkout
        - run: make ci

workflows: 
  version: 2
  build_and_test:
    jobs: 
      - build