version: 2
jobs:
    build:
      docker:
        - image: circleci/python:3.6  # primary container for the build job
      steps:
        - checkout
        - run: make
        - run: make ci
    python3.4:
      docker:
        - image: circleci/python:3.4
      steps:
        - checkout
        - run: make
        - run: make ci
    python3.5:
      docker:
        - image: circleci/python:3.5
      steps:
        - checkout
        - run: make
        - run: make ci
    python3.7:
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - run: make
        - run: make ci

workflows: 
  version: 2
  build_and_test:
    jobs: 
      - build
      - python3.4
      - python3.5
      - python3.7